name: "${project.name}"
version: "${project.version}"
author: "zml2008"
description: "${project.description}"
main: "com.zachsthings.liftplates.LiftPlatesPlugin"
commands:
    "liftplates":
        aliases: ["lp", "liftpl"]
        description: "Base command for ${project.name}"
        usage: "/<command> <version|reload>"
    "mklift":
        aliases: ["addlift", "createlift"]
        description: "Create a new lift"
        usage: "/<command> [location] <up|down>"
    "islift":
        aliases: ["liftexists", "haslift"]
        description: "Shows whether a certain point has a lift"
        usage: "/<command> <location>"
    "lslifts":
        description: "List the lifts in <world>"
        usage: "/<command> [world]"
