name: "${project.name}"
version: "${project.version}"
description: "${project.description}"
main: "com.zachsthings.liftplates.LiftPlatesPlugin"
commands:
    "liftplates":
        aliases: ["lp", "liftpl"]
        description: "Base command for ${project.name}"
        usage: "/<command> <version|reload>"
    "lift":
        aliases: ["mklift", "createlift"]
        description: "Create a new lift"
        usage: "/<command> <up|down> [location]"
